Add swift package manager integration
dreamstechnology/dreams-ios-sdk pull request #12
Opened 2024-10-23 05:37 UTC by vandervyverjohan

Added Swift Package Manager integration.

2024-10-24 13:07 UTC, jesperfrick approved these changes

2024-10-24 13:09 UTC, jesperfrick requested changes
Thank you for contributing! A good addition. One small thing, we require all commits to be signed. See instructions [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

2024-10-28 08:26 UTC, vandervyverjohan commented
Hello there!
Commits have been signed as requested.
Let me know if there is anything else.

2024-10-28 14:28 UTC, jesperfrick approved these changes

2024-10-28 14:28 UTC, merged